package cz.lttr.esch.webapp.model;
// Generated 1.2.2016 7:18:36 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventConfiguration generated by hbm2java
 */
@Entity
@Table(name="event_configuration"
    ,catalog="esch"
)
public class EventConfiguration  implements java.io.Serializable {


     private int id;
     private Event event;
     private Integer baseTimeInterval;
     private String layout;

    public EventConfiguration() {
    }

	
    public EventConfiguration(int id, Event event) {
        this.id = id;
        this.event = event;
    }
    public EventConfiguration(int id, Event event, Integer baseTimeInterval, String layout) {
       this.id = id;
       this.event = event;
       this.baseTimeInterval = baseTimeInterval;
       this.layout = layout;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="base_time_interval")
    public Integer getBaseTimeInterval() {
        return this.baseTimeInterval;
    }
    
    public void setBaseTimeInterval(Integer baseTimeInterval) {
        this.baseTimeInterval = baseTimeInterval;
    }

    
    @Column(name="layout", length=10)
    public String getLayout() {
        return this.layout;
    }
    
    public void setLayout(String layout) {
        this.layout = layout;
    }




}


