package cz.lttr.esch.webapp.model;
// Generated 1.2.2016 7:18:36 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramDay generated by hbm2java
 */
@Entity
@Table(name="program_day"
    ,catalog="esch"
)
public class ProgramDay  implements java.io.Serializable {


     private int id;
     private Event event;
     private int ordinalNumber;
     private Set<ProgramBlock> programBlocks = new HashSet<ProgramBlock>(0);

    public ProgramDay() {
    }

	
    public ProgramDay(int id, Event event, int ordinalNumber) {
        this.id = id;
        this.event = event;
        this.ordinalNumber = ordinalNumber;
    }
    public ProgramDay(int id, Event event, int ordinalNumber, Set<ProgramBlock> programBlocks) {
       this.id = id;
       this.event = event;
       this.ordinalNumber = ordinalNumber;
       this.programBlocks = programBlocks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="event_id", nullable=false)
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }

    
    @Column(name="ordinal_number", nullable=false)
    public int getOrdinalNumber() {
        return this.ordinalNumber;
    }
    
    public void setOrdinalNumber(int ordinalNumber) {
        this.ordinalNumber = ordinalNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="programDay")
    public Set<ProgramBlock> getProgramBlocks() {
        return this.programBlocks;
    }
    
    public void setProgramBlocks(Set<ProgramBlock> programBlocks) {
        this.programBlocks = programBlocks;
    }




}


