package cz.lttr.esch.webapp.model;
// Generated 1.2.2016 7:18:36 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramCategory generated by hbm2java
 */
@Entity
@Table(name="program_category"
    ,catalog="esch"
)
public class ProgramCategory  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<ProgramBlock> programBlocks = new HashSet<ProgramBlock>(0);

    public ProgramCategory() {
    }

	
    public ProgramCategory(int id) {
        this.id = id;
    }
    public ProgramCategory(int id, String name, Set<ProgramBlock> programBlocks) {
       this.id = id;
       this.name = name;
       this.programBlocks = programBlocks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="programCategory")
    public Set<ProgramBlock> getProgramBlocks() {
        return this.programBlocks;
    }
    
    public void setProgramBlocks(Set<ProgramBlock> programBlocks) {
        this.programBlocks = programBlocks;
    }




}


