package cz.lttr.esch.webapp.model;
// Generated 1.2.2016 7:18:36 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgramBlock generated by hbm2java
 */
@Entity
@Table(name="program_block"
    ,catalog="esch"
)
public class ProgramBlock  implements java.io.Serializable {


     private int id;
     private Instructor instructor;
     private ProgramCategory programCategory;
     private ProgramDay programDay;
     private String name;
     private Date startTime;
     private Date endTime;
     private int eventId;

    public ProgramBlock() {
    }

	
    public ProgramBlock(int id, int eventId) {
        this.id = id;
        this.eventId = eventId;
    }
    public ProgramBlock(int id, Instructor instructor, ProgramCategory programCategory, ProgramDay programDay, String name, Date startTime, Date endTime, int eventId) {
       this.id = id;
       this.instructor = instructor;
       this.programCategory = programCategory;
       this.programDay = programDay;
       this.name = name;
       this.startTime = startTime;
       this.endTime = endTime;
       this.eventId = eventId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="instructor_id")
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_category_id")
    public ProgramCategory getProgramCategory() {
        return this.programCategory;
    }
    
    public void setProgramCategory(ProgramCategory programCategory) {
        this.programCategory = programCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_day_id")
    public ProgramDay getProgramDay() {
        return this.programDay;
    }
    
    public void setProgramDay(ProgramDay programDay) {
        this.programDay = programDay;
    }

    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end_time", length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="event_id", nullable=false)
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }




}


